# yaml-language-server: $schema=https://goreleaser.com/static/schema.json

version: 2

builds:
  - id: "incus-compose"
    main: ./cmd/incus-compose
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X github.com/lxc/incus-compose/cmd/incus-compose/version.Version={{ .Version }}

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

# nfpms:
#   - maintainer: "Rene Jochum <rene@jochum.dev>"
#     description: Bring the familiar Docker Compose workflow to Incus containers.
#     homepage: https://github.com/lxc/incus-compose
#     license: APACHE-2.0
#     # file_name_template: "{{ .ConventionalFileName }}" # optional, better file names
#     formats:
#       - deb
#       - apk
#       - rpm

release:
  footer: >-

    ---
    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).
