# incus-compose development commands
#
# Quick start:
#   just dev-install    # Set up nested Incus for testing
#   just run <args>     # Run incus-compose against nested Incus
#   just test           # Run tests against nested Incus
#
# Local development (uses your real Incus - be careful!):
#   just run-local <args>
#   just test-local

set dotenv-load
set shell := ["bash", "-euo", "pipefail", "-c"]

[private]
default:
    @just --list

# Run `incus-compose` via `go run` against your local incus (ignores .env)
run-local *args:
    env -u INCUS_COMPOSE_URL -u INCUS_COMPOSE_CERT -u INCUS_COMPOSE_KEY -u INCUS_REMOTE -u INCUS_PROJECT go run ./cmd/incus-compose --debug {{ args }}

# Run local unit-tests, incus-facing tests are skipped.
test-local folder="./..." *args:
    INCUS_COMPOSE_TEST_LOCAL=1 go test {{ folder }} -v -coverprofile=coverage.out -covermode=atomic {{ args }}

# Lint all files.
lint folder="./...":
    golangci-lint run {{ folder }}

# Update snapshot test files
update-snapshots folder="./...":
    go clean -testcache
    CI=1 UPDATE_SNAPSHOTS=true go test {{ folder }} || true

# Dev install creates your dev environment: `just dev-install [container] [listen] [project] [image]`
dev-install container_name="local:incus-compose-test" listen='127.0.0.1:1443' project='default' image='images:debian/trixie' storagepool='detect':
    @just make-nested "{{ container_name }}" "{{ image }}" "{{ listen }}" "{{ project }}" "{{ storagepool }}"

# Run commands in the nested incus.
incus *args:
    @echo "Using remote '${INCUS_REMOTE-"local"}':"
    incus {{ args }}

# Remove generated data
clean:
    #!/usr/bin/env bash
    set -euo pipefail

    echo "Removing ./build/:"
    rm -rf ./build/

    if [[ -f .env ]]; then
        # Delete container
        echo "Trying to delete the container '${NESTED_CONTAINER}':"
        incus delete -f "${NESTED_CONTAINER}" || true

        echo "Cleaned up '${NESTED_CONTAINER}':"

        echo "Cleaning up .env"
        sed -i -e '/# START: Generated by "just dev-install"/,/# END: Generated by "just dev-install"/d' ./.env
        sed -i -e '/# START: Generated by "just ssh-tunnel-connect"/,/# END: Generated by "just ssh-tunnel-connect"/d' ./.env
    fi

    echo "Removing ./run/:"
    rm -rf ./run/

    echo "Cleanup complete"

# Build the binary
build:
    go build -o bin/incus-compose ./cmd/incus-compose

# Build ic-healthd binary
build-healthd:
    CGO_ENABLED=0 go build -tags=netgo -ldflags="-w -s -X gitlab.com/r3j0/incus-compose/cmd/ic-healthd/version.Version=`git describe --tags --always`" -trimpath -o bin/ic-healthd ./cmd/ic-healthd

# Build ic-healthd container image
build-healthd-image tag="registry.gitlab.com/r3j0/incus-compose/ic-healthd:latest":
    VERSION=`git describe --tags --always`; \
        echo ${VERSION}; \
        podman build --build-arg VERSION=${VERSION} -t {{ tag }} -f cmd/ic-healthd/Dockerfile .

# Build ic-healthd container image
release-healthd-image tag="registry.gitlab.com/r3j0/incus-compose/ic-healthd:latest": build-healthd-image
    podman push {{ tag }}

# Release incus-compose
release tag="0.0.1-dev0" healthd_image="registry.gitlab.com/r3j0/incus-compose/ic-healthd": build-healthd-image
    git tag {{ tag }} || exit 0
    git push --tags || exit 0
    podman push {{ healthd_image }}:latest
    podman tag {{ healthd_image }}:latest {{ healthd_image }}:{{ tag }}
    podman push {{ healthd_image }}:{{ tag }}
    goreleaser release --clean

# Run with local healthd binary (for testing without an explicit OCI image) (ex. just run-healthd -f test/healthd/debug/compose.yaml up )
run-healthd *args:
    @if [[ ! -f .env ]]; then echo "Error: .env not found. Run 'just dev-install' first."; exit 1; fi
    just build-healthd
    go run ./cmd/incus-compose --remote "${INCUS_REMOTE:-"local"}" {{ args }} --healthd-binary bin/ic-healthd

# Usage: just run -f test/fixtures/simple-nginx/compose.yaml config
run *args:
    @if [[ ! -f .env ]]; then echo "Error: .env not found. Run 'just dev-install' first."; exit 1; fi
    @go run ./cmd/incus-compose --remote "${INCUS_REMOTE:-"local"}" {{ args }}

# Usage: just run-debug -f test/fixtures/simple-nginx/compose.yaml config
run-debug *args:
    @if [[ ! -f .env ]]; then echo "Error: .env not found. Run 'just dev-install' first."; exit 1; fi
    @go run ./cmd/incus-compose --debug --remote "${INCUS_REMOTE:-"local"}" {{ args }}

# Run all tests against nested Incus
test folder="./..." *args:
    @if [[ ! -f .env ]]; then echo "Error: .env not found. Run 'just dev-install' first."; exit 1; fi

    go test {{ folder }} -v -coverprofile=coverage.out -covermode=atomic {{ args }}

# Run tests with coverage report
test-coverage folder="./..." *args:
    just test {{ folder }} {{ args }}
    go tool cover -func=coverage.out
    echo ""
    echo "For detailed HTML report, run: go tool cover -html=coverage.out"

# Run this before you commit.
pre-commit:
    go mod tidy
    just lint
    just test-local

[private]
make-nested container='local:incus-compose-test' image='images:debian/trixie' listen="" project="default" storagepool="detect":
    #!/usr/bin/env bash
    set -euo pipefail

    # Behavior of this script:
    #  - Uses the incus client cert
    #  - Try create nested container, ignore errors
    #  - Replace .env section

    container="{{ container }}"
    image="{{ image }}"
    listen="{{ listen }}"
    storagepool="{{ storagepool }}"

    key_file=""
    cert_file=""
    if [[ -f $HOME/.config/incus/client.crt ]] && [[ -f $HOME/.config/incus/client.key ]]; then
        key_file="$HOME/.config/incus/client.key"
        cert_file="$HOME/.config/incus/client.crt"
    fi

    # Run setup script (certificate injection is handled by the script)
    set +e
    echo "Trying to create a nested container:\n"
    INCUS_PROJECT="{{ project }}" ./scripts/setup-nested-incus.sh -c "${cert_file}" -n "${container}" -i "${image}" -r stable -l "${listen}" -p "${storagepool}"
    set -e

    if [[ -z "${listen}" ]]; then
        container_ip=$(incus list "${container}" -c4 --format json 2>/dev/null | jq -r '.[0].state.network // {} | [ .[].addresses[]? | select(.family == "inet") | .address ] | .[0] // empty' 2>/dev/null)
        if [ -z "${container_ip}" ]; then
            echo "Error: Could not get container IP"
            echo "This scripts requires you to setup the nested incus instance first, use 'just make-nested' to create it."
            exit 1
        fi

        url="https://${container_ip}:8443"
    else
        url="https://${listen}"
    fi

    ENV_DATA=$(cat <<EOF
    # START: Generated by "just dev-install", next run will overwrite this block.
    NESTED_CONTAINER="${container}"
    INCUS_COMPOSE_URL="${url}"
    INCUS_COMPOSE_CERT="${cert_file}"
    INCUS_COMPOSE_KEY="${key_file}"
    # END: Generated by "just dev-install"
    EOF
    )

    # Remove .env data
    sed -i -e '/# START: Generated by "just dev-install"/,/# END: Generated by "just dev-install"/d' ./.env >/dev/null || true

    # Append new data
    echo "${ENV_DATA}" >> ./.env

    echo -e "\nAdded the nested incus configuration to .env:\n${ENV_DATA}"
