# incus-compose development commands
#
# Quick start:
#   just dev-install    # Set up nested Incus for testing
#   just run <args>     # Run incus-compose against nested Incus
#   just test           # Run tests against nested Incus
#
# Local development (uses your real Incus - be careful!):
#   just run-local <args>
#   just test-local

set dotenv-load
set shell := ["bash", "-euo", "pipefail", "-c"]

[private]
default:
    @just --list

# Run `incus-compose` via `go run` against your local incus (ignores .env)
run-local *args:
    env -u INCUS_COMPOSE_URL -u INCUS_COMPOSE_CERT -u INCUS_COMPOSE_KEY -u INCUS_REMOTE -u INCUS_PROJECT go run ./cmd/incus-compose --debug {{ args }}

# Run local unit-tests, incus-facing tests are skipped.
test-local folder="./..." *args:
    LOGFILE=test/logs/`date +%Y%m%d-%H%M%S`-test-local.log; \
        INCUS_COMPOSE_TEST_LOCAL=1 go test {{ folder }} -v -coverprofile=coverage.out -covermode=atomic {{ args }} | tee ${LOGFILE} || EXIT_CODE=$?; \
        echo "Log: ${LOGFILE}"; \
        echo `date +%Y%m%d-%H%M%S` >> "${LOGFILE}"; \
        exit ${EXIT_CODE:-0}

# Lint all files.
lint folder="./...":
    golangci-lint run {{ folder }}

# Lint and fix all files.
fix folder="./...":
    golangci-lint run --fix {{ folder }}

# Update local snapshot test files
update-local-snapshots folder="./..." *args:
    go clean -testcache
    LOGFILE=test/logs/`date +%Y%m%d-%H%M%S`-update-local-snapshots.log; \
        NO_COLOR=1 INCUS_COMPOSE_TEST_LOCAL=1 UPDATE_SNAPSHOTS=true go test {{ folder }} -v {{ args }} | tee ${LOGFILE} || true; \
        echo `date +%Y%m%d-%H%M%S` >> "${LOGFILE}"; \
        echo "Log: ${LOGFILE}"

# Update snapshot test files that require a remote
update-snapshots folder="./..." *args:
    go clean -testcache
    LOGFILE=test/logs/`date +%Y%m%d-%H%M%S`-update-snapshots.log; \
        NO_COLOR=1 UPDATE_SNAPSHOTS=true go test {{ folder }} -v {{ args }} | tee ${LOGFILE} || true; \
        echo `date +%Y%m%d-%H%M%S` >> "${LOGFILE}"; \
        echo "Log: ${LOGFILE}"

# Dev install creates your dev environment: `just dev-install [container] [listen] [project] [image]`
dev-install container_name="local:ict" listen='127.0.0.1:1443' project='default' image='images:debian/trixie' storagepool='default':
    @just make-nested "{{ container_name }}" "{{ image }}" "{{ listen }}" "{{ project }}" "{{ storagepool }}"

# Run commands in the nested incus.
incus *args:
    @echo "Using remote '${INCUS_REMOTE-"local"}':"
    incus {{ args }}

# Remove generated data
clean:
    #!/usr/bin/env bash
    set -euo pipefail

    echo "Removing ./build/:"
    rm -rf ./build/

    if [[ -f .env ]]; then
        # Delete container
        echo "Trying to delete the container '${NESTED_CONTAINER}':"
        incus delete -f "${NESTED_CONTAINER}" || true

        echo "Cleaned up '${NESTED_CONTAINER}':"

        echo "Cleaning up .env"
        sed -i -e '/# START: Generated by "just dev-install"/,/# END: Generated by "just dev-install"/d' ./.env
        sed -i -e '/# START: Generated by "just ssh-tunnel-connect"/,/# END: Generated by "just ssh-tunnel-connect"/d' ./.env
    fi

    echo "Removing ./run/:"
    rm -rf ./run/

    echo "Cleanup complete"

# Build a release binary
build-release:
    go build -ldflags="-w -s -X gitlab.com/r3j0/incus-compose/cmd/incus-compose/version.Version=`git describe --tags --always --long --dirty="-dirty"`" -o bin/incus-compose ./cmd/incus-compose

# Build a dev binary
build:
    go build -o bin/incus-compose ./cmd/incus-compose

# Build ic-healthd binary
build-healthd:
    CGO_ENABLED=0 go build -tags=netgo -ldflags="-w -s -X gitlab.com/r3j0/incus-compose/cmd/ic-healthd/version.Version=`git describe --tags --always --long --dirty="-dirty"`" -trimpath -o bin/ic-healthd ./cmd/ic-healthd

# Build ic-healthd container image
build-healthd-image tag="registry.gitlab.com/r3j0/incus-compose/ic-healthd:latest":
    VERSION=`git describe --tags --always --long --dirty="-dirty"`; \
        echo ${VERSION}; \
        podman build --build-arg VERSION=${VERSION} -t {{ tag }} -f cmd/ic-healthd/Dockerfile .

# Build ic-healthd container image
release-healthd-image tag="registry.gitlab.com/r3j0/incus-compose/ic-healthd:latest": build-healthd-image
    podman push {{ tag }}

# Release incus-compose
release tag="0.0.1-dev0" healthd_image="registry.gitlab.com/r3j0/incus-compose/ic-healthd": build-healthd-image
    git tag {{ tag }}
    podman push {{ healthd_image }}:latest
    podman tag {{ healthd_image }}:latest {{ healthd_image }}:{{ tag }}
    podman push {{ healthd_image }}:{{ tag }}
    goreleaser release --clean
    git push --tags

# Run with local healthd binary (for testing without an explicit OCI image) (ex. just run-healthd -f test/healthd/debug/compose.yaml up )
run-healthd compose="examples/immich/compose.yaml" name="immich": build-healthd
    @if [[ ! -f .env ]]; then echo "Error: .env not found. Run 'just dev-install' first."; exit 1; fi
    go run ./cmd/incus-compose --debug -f {{ compose }} healthd up --recreate --binary bin/ic-healthd
    go run ./cmd/incus-compose -f {{ compose }} incus exec {{ name }}-ic-healthd -- tail -n 1000 -f /var/log/ic-healthd.log

# Usage: just run -f test/fixtures/simple-nginx/compose.yaml config
run *args:
    @if [[ ! -f .env ]]; then echo "Error: .env not found. Run 'just dev-install' first."; exit 1; fi
    @go run ./cmd/incus-compose --remote "${INCUS_REMOTE:-"local"}" {{ args }}

# Usage: just run-debug -f test/fixtures/simple-nginx/compose.yaml config
run-debug *args:
    @if [[ ! -f .env ]]; then echo "Error: .env not found. Run 'just dev-install' first."; exit 1; fi
    @go run ./cmd/incus-compose --debug --remote "${INCUS_REMOTE:-"local"}" {{ args }}

# Run tests against nested Incus, includes direct incus tests.
test folder="./..." *args:
    @if [[ ! -f .env ]]; then echo "Error: .env not found. Run 'just dev-install' first."; exit 1; fi
    LOGFILE=test/logs/`date +%Y%m%d-%H%M%S`-test.log; \
        NO_COLOR=1 go test {{ folder }} -v -coverprofile=coverage.out -covermode=atomic {{ args }} | tee ${LOGFILE} || EXIT_CODE=$?; \
        echo "Log: ${LOGFILE}"; \
        echo `date +%Y%m%d-%H%M%S` >> "${LOGFILE}"; \
        exit ${EXIT_CODE:-0}

# Run all tests against nested Incus, includes direct incus as well as slow tests.
test-slow folder="./..." *args:
    @if [[ ! -f .env ]]; then echo "Error: .env not found. Run 'just dev-install' first."; exit 1; fi
    LOGFILE=test/logs/`date +%Y%m%d-%H%M%S`-test-slow.log; \
        NO_COLOR=1 INCUS_COMPOSE_TEST_SLOW=1 go test {{ folder }} -v -coverprofile=coverage.out -covermode=atomic {{ args }} | tee ${LOGFILE} || EXIT_CODE=$?; \
        echo "Log: ${LOGFILE}"; \
        echo `date +%Y%m%d-%H%M%S` >> "${LOGFILE}"; \
        exit ${EXIT_CODE:-0}

# Run tests with coverage report
test-coverage folder="./..." *args:
    just test {{ folder }} {{ args }}
    go tool cover -func=coverage.out
    echo ""
    echo "For detailed HTML report, run: go tool cover -html=coverage.out"

# Purge all dangling networks (managed and 0 users) from the configured remote
purge-networks:
    #!/usr/bin/env bash
    set -euo pipefail

    remote="${INCUS_REMOTE:-local}"
    networks=$(incus network list "${remote}:" -f json | jq -r '.[] | select(.used_by | length == 0) | select(.managed == true) | .name')

    if [[ -z "${networks}" ]]; then
        echo "No dangling networks found."
        exit 1
    fi

    echo "Deleting dangling networks on remote '${remote}':"
    while IFS= read -r network; do
        echo "  Deleting: ${network}"
        incus network delete "${remote}:${network}"
    done <<< "${networks}"
    echo "Done."

# Run this before you commit.
pre-commit:
    go mod tidy
    rg -q "// TODO" **/*.go || exit 0
    just lint
    just test-local

push: pre-commit
    git push
    git push github

[private]
make-nested container='local:ict' image='images:debian/trixie' listen="127.0.0.1:1443" project="default" storagepool="default":
    #!/usr/bin/env bash
    set -euo pipefail

    # Behavior of this script:
    #  - Uses the incus client cert
    #  - Try create nested container

    container="{{ container }}"
    image="{{ image }}"
    listen="{{ listen }}"
    storagepool="{{ storagepool }}"

    key_file=""
    cert_file=""
    if [[ -f $HOME/.config/incus/client.crt ]] && [[ -f $HOME/.config/incus/client.key ]]; then
        key_file="$HOME/.config/incus/client.key"
        cert_file="$HOME/.config/incus/client.crt"
    fi

    # Run setup script (certificate injection is handled by the script)
    set +e
    echo "Trying to create a nested container:\n"
    INCUS_PROJECT="{{ project }}" ./scripts/setup-nested-incus.sh -c "${cert_file}" -n "${container}" -i "${image}" -r stable -l "${listen}" -p "${storagepool}"
    set -e

    if [[ -z "${listen}" ]]; then
        container_ip=$(incus list "${container}" -c4 --format json 2>/dev/null | jq -r '.[0].state.network // {} | [ .[].addresses[]? | select(.family == "inet") | .address ] | .[0] // empty' 2>/dev/null)
        if [ -z "${container_ip}" ]; then
            echo "Error: Could not get container IP"
            echo "This scripts requires you to setup the nested incus instance first, use 'just make-nested' to create it."
            exit 1
        fi

        url="https://${container_ip}:8443"
    else
        url="https://${listen}"
    fi

    INCUS_REMOTE="${container%%:*}" incus remote remove "${container##*:}" || exit 0
    incus remote add "${container##*:}" "${url}" --accept-certificate
