services:
  server:
    ports: !reset []
    healthcheck:
      test: ["CMD", "/usr/src/app/server/bin/immich-healthcheck"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_interval: 10s
      start_period: 5m
    networks:
      default:
        ipv4_address: 10.131.32.17

  microservices:
    healthcheck:
      test: ["CMD", "/usr/src/app/server/bin/immich-healthcheck"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_interval: 10s
      start_period: 5m

  machine-learning:
    healthcheck:
      test: ["CMD", "python3", "/usr/src/healthcheck.py"]

  redis:
    healthcheck:
      interval: 10s
      timeout: 5s
      retries: 3
      start_interval: 10s
      start_period: 1m

  database:
    healthcheck:
      test: ["CMD", "/usr/local/bin/healthcheck.sh"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_interval: 20s
      start_period: 5m

networks:
  default:
    x-incus:
      ipv4.nat: "true"
      ipv4.address: 10.131.32.1/24

volumes:
  library:
    x-incus-compose:
      pool: ${UPLOAD_POOL}
