services:
  docker-registry:
    image: direct-docker.io/library/registry:${VERSION:-3}
    environment:
      REGISTRY_HTTP_ADDR: ":5000"
      REGISTRY_PROXY_REMOTEURL: "https://registry-1.docker.io"
      REGISTRY_PROXY_TTL: "168h"
      REGISTRY_LOG_LEVEL: "${REGISTRY_LOG_LEVEL:-info}"
      REGISTRY_LOG_FIELDS_ENVIRONMENT: "production"
    volumes:
      - docker:/var/lib/registry
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://127.0.0.1:5000"]
      interval: 5s
      timeout: 5s
      retries: 6
      start_period: 30s
      start_interval: 1s

  ghcr-registry:
    image: direct-docker.io/library/registry:${VERSION:-3}
    environment:
      REGISTRY_HTTP_ADDR: ":5000"
      REGISTRY_PROXY_REMOTEURL: "https://ghcr.io"
      REGISTRY_PROXY_TTL: "168h"
      REGISTRY_LOG_LEVEL: "${REGISTRY_LOG_LEVEL:-info}"
      REGISTRY_LOG_FIELDS_ENVIRONMENT: "production"
    volumes:
      - ghcr:/var/lib/registry
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://127.0.0.1:5000"]
      interval: 5s
      timeout: 5s
      retries: 6
      start_period: 30s
      start_interval: 1s

  gitlab-registry:
    image: direct-docker.io/library/registry:${VERSION:-3}
    environment:
      REGISTRY_HTTP_ADDR: ":5000"
      REGISTRY_PROXY_REMOTEURL: "https://registry.gitlab.com"
      REGISTRY_PROXY_TTL: "168h"
      REGISTRY_LOG_LEVEL: "${REGISTRY_LOG_LEVEL:-info}"
      REGISTRY_LOG_FIELDS_ENVIRONMENT: "production"
    volumes:
      - gitlab:/var/lib/registry
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://127.0.0.1:5000"]
      interval: 5s
      timeout: 5s
      retries: 6
      start_period: 30s
      start_interval: 1s

volumes:
  docker:
  ghcr:
  gitlab:
