services:
  docker-registry:
    networks:
      default:
        ipv4_address: 10.132.32.17

  ghcr-registry:
    networks:
      default:
        ipv4_address: 10.132.32.18

  gitlab-registry:
    networks:
      default:
        ipv4_address: 10.132.32.19

networks:
  default:
    x-incus:
      ipv4.nat: "true"
      ipv4.address: 10.132.32.1/24

volumes:
  docker:
    x-incus-compose:
      pool: ${STORAGE_POOL}
  ghcr:
    x-incus-compose:
      pool: ${STORAGE_POOL}
  gitlab:
    x-incus-compose:
      pool: ${STORAGE_POOL}
