services:
  database:
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 10s
      retries: 3
      start_interval: 10s
      start_period: 4m
    networks:
      default:

  wiki:
    ports: !reset [] # do have static ip
    init: false # not supported
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://127.0.0.1:3000"] # IPv4 only
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      default:
        ipv4_address: 10.133.32.17

networks:
  default:
    x-incus:
      ipv4.nat: "true"
      ipv4.address: 10.133.32.1/24
