services:
  blog:
    build:
      args:
        BASE_URL: http://10.134.32.17
    environment:
      NGINX_ENTRYPOINT_WORKER_PROCESSES_AUTOTUNE: 1
    x-incus:
      limits.cpu: 1
    ports: !reset []
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://127.0.0.1:8080"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 30s
      start_interval: 1s
    networks:
      default:
        ipv4_address: 10.134.32.17

networks:
  default:
    x-incus:
      ipv4.nat: "true"
      ipv4.address: 10.134.32.1/24
