name: Test examples

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  # https://stackoverflow.com/a/79780883/3368468
  GOTOOLCHAIN: "go1.26.0+auto"
  REPORTS_DIR: reports

jobs:
  test-example:
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Hugo
            args: "-run TestExampleHugo"
          - name: Immich
            args: "-run TestExampleImmich -timeout 20m"
          - name: ManyDependencies
            args: "-run TestExampleManyDependencies"
          - name: WikiJS
            args: "-run TestExampleWikijs"
    runs-on: [self-hosted, incus-compose]
    timeout-minutes: 60
    permissions:
      contents: read
      checks: write # publish JUnit results as a check run
    env:
      INCUS_REMOTE: local-https
      INCUS_COMPOSE_IMAGE_CACHE: incus-compose-tests-cache
      NO_COLOR: 1
      INCUS_COMPOSE_TEST_SLOW: 1
      INCUS_COMPOSE_TEST_EXAMPLES: 1
      TEST_PROCS: 1
      EXAMPLE: TestExampleHugo
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
          cache: false

      - name: Test
        run: |
          mkdir -p "$REPORTS_DIR"

          gotestsum --rerun-fails \
            --packages="./..." \
            --junitfile "$REPORTS_DIR/junit.xml" \
            -- -count=1 -parallel "$TEST_PROCS" -timeout 20m \
               ${{ matrix.args }} 2>&1

      - name: Publish test results
        if: always()
        uses: dorny/test-reporter@v3
        with:
          name: Go Tests (${{ matrix.name }})
          path: ${{ env.REPORTS_DIR }}/junit.xml
          reporter: java-junit
          fail-on-error: false
