name: Test E2E

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  # https://stackoverflow.com/a/79780883/3368468
  GOTOOLCHAIN: "go1.26.0+auto"
  REPORTS_DIR: reports

jobs:
  test-e2e:
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        include:
          - name: stable
            remote: ict-stable
          - name: custom
            remote: ict-custom
          - name: lts
            remote: ict-lts
          - name: daily
            remote: ict-daily
    runs-on: [self-hosted, incus-compose, default]
    timeout-minutes: 120
    permissions:
      contents: read
      checks: write # publish JUnit results as a check run
    env:
      INCUS_REMOTE: ${{ matrix.remote }}
      INCUS_COMPOSE_IMAGE_CACHE: incus-compose-tests-cache
      NO_COLOR: 1
      INCUS_COMPOSE_TEST_E2E: 1
      TEST_PROCS: 2
      INCUS_COMPOSE_UP_DEPENDENCY_TIMEOUT: "2m"
      INCUS_COMPOSE_UP_TIMEOUT: "2m"
      INCUS_COMPOSE_DOWN_TIMEOUT: "1m"
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
          cache: false

      - name: Set version
        run: |
          mkdir -p "$REPORTS_DIR"
          sha="${{ github.sha }}"
          short="${sha:0:7}"
          echo "VERSION=${short}" >> "$GITHUB_ENV"
          echo "INCUS_COMPOSE_UP_HEALTHD_IMAGE=ghcr.io/lxc/incus-compose/ic-healthd:${short}" >> "$GITHUB_ENV"

      - name: Build healthd
        run: |
          just run -P cmd/ic-healthd build --os-env

      - name: Test
        run: |
          mkdir -p "$REPORTS_DIR"

          gotestsum \
            --packages="./..." \
            --junitfile "$REPORTS_DIR/junit.xml" \
            --jsonfile="$REPORTS_DIR/test.json" \
            --post-run-command "bash -c 'echo; echo Slowest tests; gotestsum tool slowest --num=10 --jsonfile=$REPORTS_DIR/test.json'" \
            -- -count=1 -parallel "$TEST_PROCS" -timeout 20m \
               -covermode=atomic -coverprofile="$REPORTS_DIR/cover.out" -v 2>&1

      - name: Publish test results
        if: always()
        uses: dorny/test-reporter@v3
        with:
          name: Go Tests (${{ matrix.name }})
          path: ${{ env.REPORTS_DIR }}/junit.xml
          reporter: java-junit
          fail-on-error: false

      - name: Publish coverage
        if: always()
        run: |
          echo -e '# Coverage\n' >> $GITHUB_STEP_SUMMARY
          go tool cover -func="$REPORTS_DIR/cover.out" >> $GITHUB_STEP_SUMMARY

  test-example:
    needs: test-e2e
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        include:
          - name: Hugo
            args: "-run TestExample/hugo"
          - name: Immich
            args: "-run TestExample/immich -timeout 20m"
          - name: ManyDependencies
            args: "-run TestExample/many-dependencies"
          - name: WikiJS
            args: "-run TestExample/wikijs"
    runs-on: [self-hosted, incus-compose]
    timeout-minutes: 60
    permissions:
      contents: read
      checks: write # publish JUnit results as a check run
    env:
      INCUS_REMOTE: ict-stable
      INCUS_COMPOSE_IMAGE_CACHE: incus-compose-tests-cache
      NO_COLOR: 1
      INCUS_COMPOSE_TEST_EXAMPLES: 1
      TEST_PROCS: 2
      EXAMPLE: TestExampleHugo
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
          cache: false

      - name: Set version
        run: |
          mkdir -p "$REPORTS_DIR"
          sha="${{ github.sha }}"
          short="${sha:0:7}"
          echo "VERSION=${short}" >> "$GITHUB_ENV"
          echo "INCUS_COMPOSE_UP_HEALTHD_IMAGE=ghcr.io/lxc/incus-compose/ic-healthd:${short}" >> "$GITHUB_ENV"

      - name: Test
        run: |
          mkdir -p "$REPORTS_DIR"

          gotestsum \
            --packages="./examples/..." \
            --junitfile "$REPORTS_DIR/junit.xml" \
            -- -count=1 -parallel "$TEST_PROCS" -timeout 20m \
               ${{ matrix.args }} 2>&1

      - name: Publish test results
        if: always()
        uses: dorny/test-reporter@v3
        with:
          name: Go Tests (${{ matrix.name }})
          path: ${{ env.REPORTS_DIR }}/junit.xml
          reporter: java-junit
          fail-on-error: false

  # goreleaser:
  #   needs: test-example
  #   runs-on: ubuntu-latest
  #   permissions:
  #     contents: write
  #     id-token: write
  #     packages: write
  #     attestations: write
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v7
  #       with:
  #         fetch-depth: 0

  #     - uses: docker/setup-buildx-action@v4.2.0
  #     - uses: sigstore/cosign-installer@v4.1.2

  #     - name: Set up Go
  #       uses: actions/setup-go@v6
  #       with:
  #         go-version-file: go.mod
  #         cache: false

  #     - name: ghcr-login
  #       if: startsWith(github.ref, 'refs/tags/v')
  #       uses: docker/login-action@v4.3.0
  #       with:
  #         registry: ghcr.io
  #         username: ${{ github.repository_owner }}
  #         password: ${{ secrets.GITHUB_TOKEN }}

  #     - name: Run GoReleaser
  #       uses: goreleaser/goreleaser-action@v7
  #       if: startsWith(github.ref, 'refs/tags/')
  #       with:
  #         # either 'goreleaser' (default) or 'goreleaser-pro'
  #         distribution: goreleaser
  #         # 'latest', 'nightly', or a semver
  #         version: "~> v2"
  #         args: release --clean
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  #     # After GoReleaser runs, attest all the files in ./dist/checksums.txt:
  #     - name: Attest Build Provenance for Archives
  #       uses: actions/attest-build-provenance@v4
  #       with:
  #         subject-checksums: ./dist/checksums.txt
  #     # After GoReleaser runs, attest all the images in ./dist/digests.txt:
  #     - name: Attest Build Provenance for Docker Images
  #       uses: actions/attest-build-provenance@v4
  #       with:
  #         subject-checksums: ./dist/digests.txt
